[colors]
  draw_bold_text_with_bright_colors = true

[window]
opacity = 0.90
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
  [window.dimensions]
  columns = 0
  lines = 0

  [window.padding]
  x = 1
  y = 0

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 11

  [font.normal]
  family = "RobotoMono Nerd Font Mono"
  style = "Medium"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[bell]
animation = "EaseOutSine"
duration = 440
color = "#868686"
command = "None"
